# Configure your database
# Port 5434, from docker-compose.yml. NOT 5432 or 5433: those are commonly held
# by another project's databases on a developer machine, and pointing migrations
# at the wrong server is silent and expensive.
import Config

config :ash, policies: [show_policy_breakdowns?: true]

config :find_me_a_flat, FindMeAFlat.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5434,
  database: "find_me_a_flat_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  pool_size: 10

config :find_me_a_flat, FindMeAFlatWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "kqDaAtCe4g5LmT3ofWeyL7wR4gnAYwBJuZCkq8I0h2jL0kAkmSPoUOSfkz9bHQCI",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:find_me_a_flat, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:find_me_a_flat, ~w(--watch)]}
  ]

# Reload browser tabs when matching files change.
config :find_me_a_flat, FindMeAFlatWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/find_me_a_flat_web/router\.ex$"E,
      ~r"lib/find_me_a_flat_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]

    # ## SSL Support
    #
    # In order to use HTTPS in development, a self-signed
    # certificate can be generated by running the following
  ]

# Enable dev routes for dashboard and mailbox
# Mix task:
#
#     mix phx.gen.cert
#
config :find_me_a_flat, dev_routes: true

# Do not include metadata nor timestamps in development logs
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       keyfile: "priv/cert/selfsigned_key.pem",
# in production as building large stacktraces may be expensive.
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # If desired, both `http:` and `https:` keys can be
  # Changing this configuration will require mix clean and a full recompile.
  # configured to run both http and https servers on
  # different ports.
  # Enable helpful, but potentially expensive runtime checks
  debug_heex_annotations: true,
  debug_attributes: true,
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
