# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
import Config

config :find_me_a_flat, FindMeAFlatWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :find_me_a_flat, FindMeAFlatWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # A load balancer probing over plain HTTP must get the answer, not a 301.
      paths: ["/healthz"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
